1. Explain pandas and its role in Data Analysis and Machine Learning.

Pandas is an open-source Python library used for data analysis and data manipulation. It provides powerful data structures like Series (1-dimensional) and DataFrame (2-dimensional) to store and work with data easily.


Role of Pandas in Data Analysis:
  It is used to read data from files such as CSV, Excel, and SQL.
  It helps in cleaning data by handling missing values and duplicate records.
  It allows filtering, sorting, and selecting specific rows and columns.
  It is used to calculate statistical values such as mean, median, maximum, and minimum.
  It makes data analysis faster and easier.
  
 Role of Pandas in Machine Learning:
  Pandas is used to prepare data before training a machine learning model.
  It helps in selecting input features and target columns.
  It converts raw data into a proper format for machine learning algorithms.
  It works well with libraries like NumPy, Matplotlib, Seaborn, and Scikit-learn.
  It is commonly used for data preprocessing before model training.

2. Differentiate between:
● Series and DataFrame
● loc[] and iloc[] functions in Pandas

(a) Difference between Series and DataFrame

Series:
A Series is a one-dimensional data structure in Pandas. It contains only one column of data and is created using pd.Series(). It is useful for storing a single list of values.


DataFrame:
A DataFrame is a two-dimensional data structure in Pandas. It contains multiple rows and columns and is created using pd.DataFrame(). It is used to store and manage tabular data, similar to an Excel sheet.


Difference:

Series is one-dimensional, while DataFrame is two-dimensional.
Series contains a single column, whereas DataFrame contains multiple columns.
Series is suitable for a single type of data, while DataFrame can store different types of data in different columns.


(b) Difference between loc[] and iloc[]


loc[]:
The loc[] function is used to access data using row and column labels (names). It works with the actual labels present in the DataFrame.


iloc[]:
The iloc[] function is used to access data using row and column index positions. It works only with integer index values.


Difference:


loc[] uses labels or names to select data.
iloc[] uses integer index positions to select data.
loc[] is label-based indexing, whereas iloc[] is integer-based indexing.

3. Create a Pandas DataFrame using the dataset below: Name Age Marks Amit 20 85 Neha 21 90 Rahul 19 78 Sneha 22 88 a) Tasks: ● Display first 2 rows ● Display only Name and Marks columns ● Add a new column named “Result” ● Display students with marks greater than 80 b) Expected Concepts: ● pd.DataFrame() ● head() ● Column Selection ● Conditional Filtering

In [2]:
import pandas as pd

data = {
    "Name": ["Amit", "Neha", "Rahul", "Sneha"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)

print("Original DataFrame")
print(df)

print("\nFirst 2 Rows")
print(df.head(2))

print("\nName and Marks Columns")
print(df[["Name", "Marks"]])

df["Result"] = "Pass"

print("\nDataFrame after adding Result column")
print(df)

print("\nStudents with Marks greater than 80")
print(df[df["Marks"] > 80])

Original DataFrame
    Name  Age  Marks
0   Amit   20     85
1   Neha   21     90
2  Rahul   19     78
3  Sneha   22     88

First 2 Rows
   Name  Age  Marks
0  Amit   20     85
1  Neha   21     90

Name and Marks Columns
    Name  Marks
0   Amit     85
1   Neha     90
2  Rahul     78
3  Sneha     88

DataFrame after adding Result column
    Name  Age  Marks Result
0   Amit   20     85   Pass
1   Neha   21     90   Pass
2  Rahul   19     78   Pass
3  Sneha   22     88   Pass

Students with Marks greater than 80
    Name  Age  Marks Result
0   Amit   20     85   Pass
1   Neha   21     90   Pass
3  Sneha   22     88   Pass

4. Create a DataFrame using the dataset below:
Name Age Salary
A 25 30000
B NaN 40000
C 27 NaN
D 24 35000
a) Tasks:
● Identify missing values
● Fill missing Age with average age
● Fill missing Salary with median salary
● Display cleaned dataset
b) Expected Concepts:
● isnull()
● fillna()
● mean()
● median()

In [3]:
import pandas as pd
import numpy as np

data = {
    "Name": ["A", "B", "C", "D"],
    "Age": [25, np.nan, 27, 24],
    "Salary": [30000, 40000, np.nan, 35000]
}

df = pd.DataFrame(data)

print("Original DataFrame")
print(df)

print("\nMissing Values")
print(df.isnull().sum())

avg_age = df["Age"].mean()
df["Age"] = df["Age"].fillna(avg_age)

median_salary = df["Salary"].median()
df["Salary"] = df["Salary"].fillna(median_salary)

print("\nCleaned DataFrame")
print(df)

Original DataFrame
  Name   Age   Salary
0    A  25.0  30000.0
1    B   NaN  40000.0
2    C  27.0      NaN
3    D  24.0  35000.0

Missing Values
Name      0
Age       1
Salary    1
dtype: int64

Cleaned DataFrame
  Name        Age   Salary
0    A  25.000000  30000.0
1    B  25.333333  40000.0
2    C  27.000000  35000.0
3    D  24.000000  35000.0

5. Dataset Link: Iris Dataset
a) Tasks:
● Load CSV file using Pandas
● Display dataset information
● Find:
o Total rows and columns
o Average sepal length
o Different species names
● Display summary statistics
b) Expected Concepts:
● pd.read_csv()
● info()
● describe()
● unique()

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv(r"C:\Users\Ajit\Downloads\Iris.csv")

In [12]:
df = pd.read_csv("Iris.csv")

In [9]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [15]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [16]:
print("First 5 Rows")
print(df.head())

print("\nDataset Information")
df.info()

print("\nTotal Rows and Columns")
print(df.shape)

print("\nAverage Sepal Length")
print(df["SepalLengthCm"].mean())

print("\nDifferent Species Names")
print(df["Species"].unique())

print("\nSummary Statistics")
print(df.describe())

First 5 Rows
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

Total Rows and Columns
(150, 6)

Average Sepal Length
5.843333333333334

Different Species Names
<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

Summary Statistics
               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000